import { useState, useEffect, useCallback } from "react";
import { Share2, Download, Copy, X, Loader2, Sparkles, Trophy, ExternalLink } from "lucide-react";
import { copyToClipboard, getPublishedOrigin, getPublishedUrl } from "@/lib/clipboard";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

interface ShareCardProps {
  creatorId: string;
  creatorName: string;
  rank?: number;
  votesCount?: number;
  avatarUrl?: string;
  category?: string;
  onClose: () => void;
  autoGenerate?: boolean;
  onShareBonus?: () => void;
}

const ShareCard = ({ creatorId, creatorName, rank, votesCount, avatarUrl, category, onClose, autoGenerate = false, onShareBonus }: ShareCardProps) => {
  const [imageDataUrl, setImageDataUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);
  const [bonusClaimed, setBonusClaimed] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const generateCard = useCallback(async () => {
    setLoading(true);
    setError(false);
    try {
      const W = 1200;
      const H = 630;
      const canvas = document.createElement("canvas");
      canvas.width = W;
      canvas.height = H;
      const ctx = canvas.getContext("2d")!;

      // Background
      const bgGrad = ctx.createLinearGradient(0, 0, W, H);
      bgGrad.addColorStop(0, "#0f172a");
      bgGrad.addColorStop(0.5, "#1a1040");
      bgGrad.addColorStop(1, "#0a1525");
      ctx.fillStyle = bgGrad;
      ctx.fillRect(0, 0, W, H);

      // Decorative glows
      ctx.globalAlpha = 0.12;
      const g1 = ctx.createRadialGradient(150, 200, 0, 150, 200, 350);
      g1.addColorStop(0, "#8B5CF6");
      g1.addColorStop(1, "transparent");
      ctx.fillStyle = g1;
      ctx.fillRect(0, 0, W, H);

      const g2 = ctx.createRadialGradient(W - 200, H - 150, 0, W - 200, H - 150, 300);
      g2.addColorStop(0, "#06B6D4");
      g2.addColorStop(1, "transparent");
      ctx.fillStyle = g2;
      ctx.fillRect(0, 0, W, H);
      ctx.globalAlpha = 1;

      // Glass card area
      const cardX = 80;
      const cardY = 60;
      const cardW = W - 160;
      const cardH = H - 120;
      ctx.fillStyle = "rgba(255, 255, 255, 0.04)";
      roundRect(ctx, cardX, cardY, cardW, cardH, 28);
      ctx.fill();
      ctx.strokeStyle = "rgba(255, 255, 255, 0.1)";
      ctx.lineWidth = 1.5;
      roundRect(ctx, cardX, cardY, cardW, cardH, 28);
      ctx.stroke();

      // Load avatar
      let avatarLoaded = false;
      const avatarImg = new Image();
      avatarImg.crossOrigin = "anonymous";
      if (avatarUrl) {
        await new Promise<void>((resolve) => {
          avatarImg.onload = () => { avatarLoaded = true; resolve(); };
          avatarImg.onerror = () => resolve();
          const url = avatarUrl.startsWith("/") ? `${window.location.origin}${avatarUrl}` : avatarUrl;
          avatarImg.src = url;
          setTimeout(resolve, 2000);
        });
      }

      // Avatar
      const avSize = 160;
      const avX = 220;
      const avY = H / 2;

      // Avatar glow ring
      const ringGrad = ctx.createLinearGradient(avX - avSize / 2, avY - avSize / 2, avX + avSize / 2, avY + avSize / 2);
      ringGrad.addColorStop(0, "#8B5CF6");
      ringGrad.addColorStop(1, "#06B6D4");
      ctx.beginPath();
      ctx.arc(avX, avY, avSize / 2 + 6, 0, Math.PI * 2);
      ctx.fillStyle = ringGrad;
      ctx.fill();

      if (avatarLoaded) {
        ctx.save();
        ctx.beginPath();
        ctx.arc(avX, avY, avSize / 2, 0, Math.PI * 2);
        ctx.clip();
        ctx.drawImage(avatarImg, avX - avSize / 2, avY - avSize / 2, avSize, avSize);
        ctx.restore();
      } else {
        ctx.beginPath();
        ctx.arc(avX, avY, avSize / 2, 0, Math.PI * 2);
        ctx.fillStyle = "#1a1040";
        ctx.fill();
        ctx.fillStyle = "#8B5CF6";
        ctx.font = "bold 56px 'Noto Sans KR', sans-serif";
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        ctx.fillText(creatorName.slice(0, 2), avX, avY);
      }

      // Right side content
      const textX = 380;

      // "Rank⚡it" logo
      ctx.font = "bold 28px 'Space Grotesk', Arial, sans-serif";
      ctx.textAlign = "left";
      ctx.textBaseline = "middle";
      ctx.fillStyle = "#8B5CF6";
      ctx.fillText("Rank", textX, 130);
      const rkW = ctx.measureText("Rank").width;
      ctx.fillStyle = "#06B6D4";
      ctx.fillText("⚡", textX + rkW, 130);
      const bW = ctx.measureText("⚡").width;
      ctx.fillStyle = "#a78bfa";
      ctx.font = "300 28px 'Space Grotesk', Arial, sans-serif";
      ctx.fillText("it", textX + rkW + bW, 130);

      // Category badge
      if (category) {
        ctx.font = "600 18px 'Noto Sans KR', sans-serif";
        const catText = category;
        const catW = ctx.measureText(catText).width + 24;
        ctx.fillStyle = "rgba(139, 92, 246, 0.15)";
        roundRect(ctx, textX, 160, catW, 32, 16);
        ctx.fill();
        ctx.fillStyle = "#a78bfa";
        ctx.textBaseline = "middle";
        ctx.fillText(catText, textX + 12, 176);
      }

      // Creator name
      ctx.fillStyle = "#ffffff";
      ctx.font = "bold 52px 'Noto Sans KR', sans-serif";
      ctx.textBaseline = "middle";
      let displayName = creatorName;
      while (ctx.measureText(displayName).width > cardW - 340 && displayName.length > 3) {
        displayName = displayName.slice(0, -1);
      }
      if (displayName !== creatorName) displayName += "…";
      ctx.fillText(displayName, textX, 250);

      // Rank badge
      if (rank) {
        const rankY = 330;
        ctx.fillStyle = "rgba(139, 92, 246, 0.15)";
        roundRect(ctx, textX, rankY - 24, 160, 48, 12);
        ctx.fill();
        ctx.strokeStyle = "rgba(139, 92, 246, 0.4)";
        ctx.lineWidth = 1.5;
        roundRect(ctx, textX, rankY - 24, 160, 48, 12);
        ctx.stroke();
        ctx.fillStyle = "#8B5CF6";
        ctx.font = "bold 28px 'Space Grotesk', sans-serif";
        ctx.fillText(`🏆 #${rank}`, textX + 16, rankY);
      }

      // Votes
      if (votesCount !== undefined) {
        const voteX = rank ? textX + 190 : textX;
        const voteY = 330;
        ctx.fillStyle = "rgba(6, 182, 212, 0.12)";
        const voteText = `${votesCount.toLocaleString()}표`;
        ctx.font = "bold 24px 'Noto Sans KR', sans-serif";
        const vtW = ctx.measureText(voteText).width + 28;
        roundRect(ctx, voteX, voteY - 24, vtW, 48, 12);
        ctx.fill();
        ctx.strokeStyle = "rgba(6, 182, 212, 0.35)";
        ctx.lineWidth = 1.5;
        roundRect(ctx, voteX, voteY - 24, vtW, 48, 12);
        ctx.stroke();
        ctx.fillStyle = "#06B6D4";
        ctx.fillText(voteText, voteX + 14, voteY);
      }

      // CTA
      ctx.fillStyle = "#64748b";
      ctx.font = "500 22px 'Noto Sans KR', sans-serif";
      ctx.fillText("나도 투표하러 가기 → rankit.today", textX, 430);

      // Bottom decorative line
      const lineGrad = ctx.createLinearGradient(cardX + 40, 0, cardX + cardW - 40, 0);
      lineGrad.addColorStop(0, "transparent");
      lineGrad.addColorStop(0.3, "#8B5CF680");
      lineGrad.addColorStop(0.7, "#06B6D480");
      lineGrad.addColorStop(1, "transparent");
      ctx.strokeStyle = lineGrad;
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(cardX + 40, H - 90);
      ctx.lineTo(cardX + cardW - 40, H - 90);
      ctx.stroke();

      // Watermark
      ctx.fillStyle = "rgba(255,255,255,0.15)";
      ctx.font = "400 16px 'Space Grotesk', sans-serif";
      ctx.textAlign = "right";
      ctx.fillText("rankit.today", W - 100, H - 75);

      const dataUrl = canvas.toDataURL("image/png");
      setImageDataUrl(dataUrl);
    } catch (e) {
      console.error(e);
      setError(true);
      toast.error("공유 카드 생성에 실패했습니다.");
    } finally {
      setLoading(false);
    }
  }, [creatorName, rank, votesCount, avatarUrl, category]);

  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated && !imageDataUrl && !loading) {
      setHasAutoGenerated(true);
      generateCard();
    }
  }, [autoGenerate, hasAutoGenerated, imageDataUrl, loading, generateCard]);

  const shareUrl = `${getPublishedOrigin()}/creator/${creatorId}`;
  const shareText = `${creatorName}에게 투표했어요! 🏆 Rank It에서 확인하세요!`;

  const handleCopyLink = async () => {
    const ok = await copyToClipboard(shareUrl);
    if (ok) toast.success("링크가 복사되었습니다!");
    else toast.error("복사에 실패했습니다.");
  };

  const claimShareBonus = () => {
    if (!bonusClaimed && onShareBonus) {
      setBonusClaimed(true);
      onShareBonus();
      toast.success("🎁 공유 보너스! 투표권 +1을 받았습니다!");
    }
  };

  const handleNativeShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({ title: `Rank It - ${creatorName}`, text: shareText, url: shareUrl });
        claimShareBonus();
      } catch { /* cancelled */ }
    } else {
      handleCopyLink();
    }
  };

  const handleShareTwitter = () => {
    const text = encodeURIComponent(shareText);
    window.open(`https://twitter.com/intent/tweet?text=${text}&url=${encodeURIComponent(shareUrl)}`, "_blank");
    claimShareBonus();
  };

  const handleShareFacebook = () => {
    window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`, "_blank");
  };

  const handleDownload = () => {
    if (!imageDataUrl) return;
    const a = document.createElement("a");
    a.href = imageDataUrl;
    a.download = `rankit-${creatorName}.png`;
    a.click();
    toast.success("이미지가 다운로드되었습니다!");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-start sm:items-center justify-center bg-background/60 backdrop-blur-md p-4 pt-4 sm:pt-4 animate-fade-in overflow-y-auto">
      {/* Ambient glow effects */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-[hsl(var(--neon-purple))] rounded-full opacity-10 blur-[100px] animate-pulse" />
        <div className="absolute bottom-1/4 right-1/4 w-48 h-48 bg-[hsl(var(--neon-cyan))] rounded-full opacity-10 blur-[80px] animate-pulse" style={{ animationDelay: "1s" }} />
      </div>

      <div className="relative w-full max-w-sm animate-scale-in">
        <div className="absolute -inset-[1px] rounded-2xl bg-gradient-to-br from-[hsl(var(--neon-purple))] via-[hsl(var(--neon-cyan)/0.3)] to-[hsl(var(--neon-purple)/0.5)] opacity-60 blur-[1px]" />
        
        <div className="relative rounded-2xl bg-[hsl(var(--glass))] border border-[hsl(var(--glass-border))] backdrop-blur-xl p-5 space-y-4 overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-bl from-[hsl(var(--neon-purple)/0.15)] to-transparent rounded-bl-full" />
          <div className="absolute bottom-0 left-0 w-24 h-24 bg-gradient-to-tr from-[hsl(var(--neon-cyan)/0.1)] to-transparent rounded-tr-full" />

          <button
            onClick={onClose}
            className="absolute top-3 right-3 z-10 p-1.5 rounded-full bg-[hsl(var(--muted)/0.5)] text-muted-foreground hover:text-foreground hover:bg-[hsl(var(--muted))] transition-all"
          >
            <X className="w-4 h-4" />
          </button>

          <div className="relative text-center space-y-1.5 pt-1">
            <div className="flex items-center justify-center gap-2">
              <Sparkles className="w-4 h-4 text-[hsl(var(--neon-cyan))]" />
              <h3 className="text-lg font-bold bg-gradient-to-r from-[hsl(var(--neon-purple))] to-[hsl(var(--neon-cyan))] bg-clip-text text-transparent">
                SNS 공유하기
              </h3>
              <Sparkles className="w-4 h-4 text-[hsl(var(--neon-purple))]" />
            </div>
            <p className="text-xs text-muted-foreground">{creatorName}의 순위를 친구에게 알려주세요!</p>
          </div>

          {(rank || votesCount) && (
            <div className="relative flex items-center justify-center gap-4 py-2">
              {rank && (
                <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-[hsl(var(--neon-purple)/0.1)] border border-[hsl(var(--neon-purple)/0.2)]">
                  <Trophy className="w-3.5 h-3.5 text-[hsl(var(--neon-purple))]" />
                  <span className="text-xs font-bold text-[hsl(var(--neon-purple))]">#{rank}</span>
                </div>
              )}
              {votesCount !== undefined && (
                <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-[hsl(var(--neon-cyan)/0.1)] border border-[hsl(var(--neon-cyan)/0.2)]">
                  <span className="text-xs font-bold text-[hsl(var(--neon-cyan))]">{votesCount.toLocaleString()}표</span>
                </div>
              )}
            </div>
          )}

          <div className="relative rounded-xl border border-[hsl(var(--glass-border))] bg-[hsl(var(--background)/0.5)] p-3 min-h-[160px] flex items-center justify-center overflow-hidden">
            {loading ? (
              <div className="flex flex-col items-center gap-3 text-muted-foreground">
                <div className="relative">
                  <div className="absolute inset-0 rounded-full bg-[hsl(var(--neon-purple)/0.2)] blur-md animate-pulse" />
                  <Loader2 className="relative w-8 h-8 animate-spin text-[hsl(var(--neon-purple))]" />
                </div>
                <span className="text-sm font-medium text-foreground/80">카드 생성 중... ✨</span>
              </div>
            ) : imageDataUrl ? (
              <img
                src={imageDataUrl}
                alt="Share card"
                className="w-full rounded-lg shadow-lg shadow-[hsl(var(--neon-purple)/0.15)] transition-transform hover:scale-[1.02]"
              />
            ) : error ? (
              <div className="text-center space-y-3 py-2">
                <p className="text-sm text-muted-foreground">카드 생성에 실패했습니다 😢</p>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={generateCard}
                  className="border-[hsl(var(--neon-purple)/0.3)] hover:border-[hsl(var(--neon-purple)/0.6)] hover:bg-[hsl(var(--neon-purple)/0.1)]"
                >
                  다시 시도
                </Button>
              </div>
            ) : (
              <button
                onClick={generateCard}
                className="group relative px-6 py-3 rounded-xl font-medium text-sm transition-all duration-300 overflow-hidden"
              >
                <div className="absolute inset-0 bg-gradient-to-r from-[hsl(var(--neon-purple))] to-[hsl(var(--neon-cyan))] opacity-90 group-hover:opacity-100 transition-opacity" />
                <div className="absolute inset-0 bg-gradient-to-r from-[hsl(var(--neon-cyan))] to-[hsl(var(--neon-purple))] opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                <span className="relative flex items-center gap-2 text-primary-foreground">
                  <Sparkles className="w-4 h-4" />
                  공유 카드 생성하기
                  <Share2 className="w-4 h-4" />
                </span>
              </button>
            )}
          </div>

          {imageDataUrl && (
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                className="flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl text-sm font-medium border border-[hsl(var(--glass-border))] bg-[hsl(var(--glass)/0.5)] hover:border-[hsl(var(--neon-cyan)/0.4)] hover:bg-[hsl(var(--neon-cyan)/0.05)] transition-all"
              >
                <Download className="w-4 h-4 text-[hsl(var(--neon-cyan))]" />
                <span>저장</span>
              </button>
              <button
                onClick={handleCopyLink}
                className="flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl text-sm font-medium border border-[hsl(var(--glass-border))] bg-[hsl(var(--glass)/0.5)] hover:border-[hsl(var(--neon-purple)/0.4)] hover:bg-[hsl(var(--neon-purple)/0.05)] transition-all"
              >
                <Copy className="w-4 h-4 text-[hsl(var(--neon-purple))]" />
                <span>링크 복사</span>
              </button>
            </div>
          )}

          {onShareBonus && !bonusClaimed && (
            <div className="flex items-center gap-2 p-2.5 rounded-xl bg-gradient-to-r from-[hsl(var(--neon-purple)/0.15)] to-[hsl(var(--neon-cyan)/0.15)] border border-[hsl(var(--neon-purple)/0.3)] animate-pulse">
              <span className="text-base">🎁</span>
              <span className="text-xs font-bold text-foreground flex-1">SNS 공유하고 투표권 +1 받기!</span>
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-[hsl(var(--neon-cyan)/0.2)] text-[hsl(var(--neon-cyan))] font-bold">FREE</span>
            </div>
          )}
          {bonusClaimed && (
            <div className="flex items-center gap-2 p-2.5 rounded-xl bg-[hsl(var(--neon-cyan)/0.1)] border border-[hsl(var(--neon-cyan)/0.3)]">
              <span className="text-base">✅</span>
              <span className="text-xs font-medium text-[hsl(var(--neon-cyan))]">공유 보너스 투표권 +1 지급 완료!</span>
            </div>
          )}

          <div className="grid grid-cols-2 gap-2">
            <button
              onClick={handleNativeShare}
              className="group relative flex items-center justify-center gap-2 py-3 rounded-xl text-sm font-medium border border-[hsl(var(--glass-border))] bg-[hsl(var(--glass)/0.3)] hover:border-[hsl(var(--neon-cyan)/0.4)] hover:shadow-[0_0_15px_hsl(var(--neon-cyan)/0.1)] transition-all duration-300"
            >
              <span className="text-base">📲</span>
              <span>공유하기</span>
              <ExternalLink className="w-3 h-3 opacity-0 group-hover:opacity-50 transition-opacity" />
            </button>
            <button
              onClick={handleShareTwitter}
              className="group relative flex items-center justify-center gap-2 py-3 rounded-xl text-sm font-medium border border-[hsl(var(--glass-border))] bg-[hsl(var(--glass)/0.3)] hover:border-[hsl(210_100%_50%/0.4)] hover:shadow-[0_0_15px_hsl(210_100%_50%/0.1)] transition-all duration-300"
            >
              <span className="text-base font-bold">𝕏</span>
              <span>트위터</span>
            </button>
            <button
              onClick={async () => {
                const ok = await copyToClipboard(getPublishedUrl());
                if (ok) toast.success("링크가 복사되었습니다!");
                else toast.error("복사에 실패했습니다.");
                claimShareBonus();
              }}
              className="group relative flex items-center justify-center gap-2 py-3 rounded-xl text-sm font-medium border border-[hsl(var(--glass-border))] bg-[hsl(var(--glass)/0.3)] hover:border-[hsl(var(--neon-cyan)/0.4)] hover:shadow-[0_0_15px_hsl(var(--neon-cyan)/0.1)] transition-all duration-300"
            >
              <Copy className="w-4 h-4 text-[hsl(var(--neon-cyan))]" />
              <span>링크 복사</span>
            </button>
            <button
              onClick={handleShareFacebook}
              className="group relative flex items-center justify-center gap-2 py-3 rounded-xl text-sm font-medium border border-[hsl(var(--glass-border))] bg-[hsl(var(--glass)/0.3)] hover:border-[hsl(220_90%_55%/0.4)] hover:shadow-[0_0_15px_hsl(220_90%_55%/0.1)] transition-all duration-300"
            >
              <span className="text-base">📘</span>
              <span>페이스북</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

export default ShareCard;
